server:
  port: 8888

logging:
  level:
    root: debug

spring:
  profiles:
    active: dev
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations